#!/bin/sh
#feh --no-fehbg --bg-fill ~/.wallpaper/23.jpg
#feh --no-fehbg --bg-fill ~/.wallpaper/24.jpg
#feh --no-fehbg --bg-fill ~/.wallpaper/25.jpg
#feh --no-fehbg --bg-fill ~/.wallpaper/26.jpg
#feh --no-fehbg --bg-fill ~/.wallpaper/27.jpg
#feh --no-fehbg --bg-fill ~/.wallpaper/28.jpg
#feh --no-fehbg --bg-fill ~/.wallpaper/29.jpg
#feh  --no-fehbg --bg-fill ~/.wallpaper/30.jpg
#feh  --no-fehbg --bg-fill ~/.wallpaper/31.jpg
#feh  --no-fehbg --bg-fill ~/.wallpaper/32.png
#feh  --no-fehbg --bg-fill ~/.wallpaper/33.png
#feh  --no-fehbg --bg-fill ~/.wallpaper/34.png
#feh  --no-fehbg --bg-fill ~/.wallpaper/35.png
#feh  --no-fehbg --bg-fill ~/.wallpaper/36.png
feh  --no-fehbg --bg-fill ~/.wallpaper/37.png
#feh  --no-fehbg --bg-fill ~/.wallpaper/38.jpg
